[package]
name = "command_explain"
version.workspace = true
edition.workspace = true

[dependencies]
phase_loading.workspace = true
phase_evaluation.workspace = true
lib_label.workspace = true
crossterm.workspace = true