[package]
name = "command_query"
version.workspace = true
edition.workspace = true

[dependencies]
lib_label.workspace = true
phase_loading.workspace = true
owo-colors.workspace = true
line-numbers = "0.4.0"
