[package]
name = "phase_loading"
version.workspace = true
edition.workspace = true

[dependencies]
# Internal
lib_label.workspace = true

# External
toml.workspace = true
serde.workspace = true
log.workspace = true
derive_more.workspace = true
ordermap.workspace = true
ignore = "0.4.23"