[package]
name = "command_aquery"
version.workspace = true
edition.workspace = true

[dependencies]
phase_loading.workspace = true
phase_evaluation.workspace = true
lib_label.workspace = true
lib_graph_exec.workspace = true
owo-colors.workspace = true