[svg]
puzzle = "Environment / Puzzle"
sun = "Environment / Sun"
bulb = "Environment / Bulb"
planet = "Environment / Planet"
leaf = "Environment / Leaf"
first_aid = "Environment / First_Aid"
moon = "Environment / Moon"
cookie = "Environment / Cookie"
water_drop = "Environment / Water_Drop"
cupcake = "Environment / Cupcake"
rainbow = "Environment / Rainbow"
coffee = "Environment / Coffee"
