[icons]
Puzzle = "Environment / Puzzle"
Sun = "Environment / Sun"
Bulb = "Environment / Bulb"
Planet = "Environment / Planet"
Leaf = "Environment / Leaf"
FirstAid = "Environment / First_Aid"
Moon = "Environment / Moon"
Cookie = "Environment / Cookie"
WaterDrop = "Environment / Water_Drop"
Cupcake = "Environment / Cupcake"
Rainbow = "Environment / Rainbow"
