name: "Pull Request"

on:
  push:
    branches: [ master ]
    paths: [ 'Cargo.toml', 'src/**' ]
  pull_request:

jobs:
  unit-tests:
    name: Run all tests (${{ matrix.platform.target }})
    strategy:
      fail-fast: false
      matrix:
        platform:
          - runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-gnu

          - runs-on: windows-latest
            target: x86_64-pc-windows-msvc

          - runs-on: macOS-latest
            target: aarch64-apple-darwin

        toolchain:
          - stable

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        
        - name: Run tests
          if: ${{ !startsWith(matrix.platform.os-name, 'Windows') }}
          uses: houseabsolute/actions-rust-cross@v1
          with:
            command: test
            target: ${{ matrix.platform.target }}
            toolchain: ${{ matrix.toolchain }}
