on:
  push:
    tags:
      - "v*" # Run when tag matches v*, i.e. v1.0, v20.15.10

name: Release

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-gnu

          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc

          - os-name: macOS-aarch64
            runs-on: macOS-latest
            target: aarch64-apple-darwin
        toolchain:
          - stable

    runs-on: ${{ matrix.platform.runs-on }}
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build binary (Linux / macOS)
        if: ${{ !startsWith(matrix.platform.os-name, 'Windows') }}
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          toolchain: ${{ matrix.toolchain }}
          strip: true

      - name: Install WIX (Windows)
        if: ${{ startsWith(matrix.platform.os-name, 'Windows') }}
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-wix
          version: "0.3.9"

      - name: Build binary (Windows)
        if: ${{ startsWith(matrix.platform.os-name, 'Windows') }}
        uses: houseabsolute/actions-rust-cross@v1
        with:
          working-directory: ./app
          command: wix
          target: ${{ matrix.platform.target }}
          args: "-p figx --nocapture"
          toolchain: ${{ matrix.toolchain }}
          strip: false

      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: figx
          target: ${{ matrix.platform.target }}
